name: "Copilot Setup Steps"

# This workflow runs before the Copilot coding agent starts its ephemeral environment.
# It must live on the default branch (usually `main`) for Copilot to pick it up.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` for Copilot to recognize it.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JavaScript dependencies
        run: |
          npm ci

      # Optional quick verification step. Uncomment if you want Copilot's environment
      # to validate that the project builds successfully before starting a session.
      # - name: Build (optional verification)
      #   run: |
      #     npm run build --if-present
