name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_ed25519
          ${{ secrets.PI_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_ed25519
