name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Raspberry Pi
      run: |
        ssh ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
          cd /home/pi/nextjs-app
          git pull origin main
          pnpm install
          pnpm build
          pm2 restart my-next-app
        EOF
