name: Deploy queue-hub to pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build app
        run: |
          pnpm build

      - name: Restart app with PM2
        run: |
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi
          pm2 restart queue-hub || pm2 start npm --name queue-hub -- run start
